### ISSUE TITLE
NullPointer in HashMap<String, Object> mCheckedItems 

### ISSUE THREAD

**Issue by danielisrael** [anton46/Foursquare-CollectionPicker#5]
When select one tag, CollectionPicker.this.mCheckedItems.put (item.id, item); NullPointer return as the mCheckedItems variable is null.

**Comment by sonph** [comment]
I've encountered the same problem. Cloning the code and add to Android Studio then modify `CollectionPicker.java:38` to `private HashMap<String, Object> mCheckedItems = new HashMap<>();` solves the problem.

Also method `setCheckedItems(HashMap)` which sets the values for `mCheckedItems` in `CollectionPicker.java` is never called.

**Comment by anton46** [comment]
Please update the library version to `1.0.2`
